### ISSUE TITLE
Spreading the program over multiple days?

### ISSUE THREAD

**Issue by pazz** [lorenzschmid/jekyll-congress#10]
I am hosting a conference with a 3 day program. If someone has used this template for such events before, I'd be very happy to get suggestions for

- adjusting the datastructure and includes for the program,
- adding social events or other non-talks to the program

From the point of view of this project, please interpret this issue as a long-term feature request. :)

**Comment by lorenzschmid** [comment]
Thanks for your input. Since this template was mainly made with our own, one-day [conference](https://www.digitale-gesellschaft.ch/kongress/) in mind, there was never any need to add a multi-day program. But I am always open for PRs.

In terms of how to tackle such an implementation: I would propose to add an additional hierarchical layer with the day to each room in the `program.yml` data file. From there you would have to update the rendering files, most importantly `program/index.html`, `_includes/get_talk_time.html`, and `_includes/show_talk_time.html` (and probably some others too). Overall I think it is quite feasible.

**Comment by pazz** [comment]
Thanks for the pointers. I'll have some time later this year (my event is only in March'21)
and will send a PR with my proposed solution when I got one.

I believe that at least among the scientific community conferences over more than one day are commonplace and this will be a much sought-after feature.

Side-note: one other "killer feature" for us webs-noobs who organize conferences would be a variant of the python script that
eats a spreadsheet file which can be maintained by non-techy administrators.

Thanks again!
P

**Comment by lorenzschmid** [comment]
You're welcome. 

> Side-note: one other "killer feature" for us webs-noobs who organize conferences would be a variant of the python script that eats a spreadsheet file which can be maintained by non-techy administrators.

I understand well and as said are always open for any PR. As a small NGO our focus is on our own conference and the needs for this template which arise from there. Concerning that we have only one import of data a year (with our yearly conference), there is little point for us to spend time on writing a fancier import script/interface. But of course that does not mean we will not consider it sometime in the future or are welcoming PRs. In any case you might want to open a separate issue for this.

**Comment by pazz** [comment]
Of course. I'll just send around what I have at the time I'm done and have cleaned it up.
Thanks for sharing your code!

**Comment by lorenzschmid** [comment]
Transferred to the new repository https://github.com/DigitaleGesellschaft/jekyll-theme-conference/issues/2
